# Generated by Django 6.0.4 on 2026-04-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descirption',
            new_name='description',
        ),
    ]
